# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ce564a01507721dbcd8b2af828c3079524a00c241a8a9945cf797add8c4e9d5c1294b354d449a0211c5976d8edd96dbb883c8b6538db847653c81c3987129f

test:
  secret_key_base: 6d5dd8a7d3250d407d5cf0fbb6d1974cbc7e40ffe1e8d0a239f656e46d7b5988226280f0f8250f9b14aefdf4900571e524cfa020dd6475ec893218fbc4945756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
